#!/bin/bash

programs=("sudo" "intel-ucode" "wget")

programs+=("efibootmgr") #For EFISTUB
programs+=("networkmanager" "nm-connection-editor" "network-manager-applet") #Networkmanager, graphical interface and system tray
programs+=("xorg-server" "xorg-setxkbmap" "xorg-xset" "xorg-xrandr" "xorg-xinit" "xorg-xrdb") #Xorg server and components
programs+=("pulseaudio" "pulseaudio-alsa" "pulsemixer" "pavucontrol") #Pulseaudio, pulse for alsa, command line mixer and a graphical mixer
programs+=("xterm") #xterm Terminal
programs+=("firefox") #Firefox browser
programs+=("numlockx") #For numlock activation on X startup
programs+=("i3-wm" "i3-status") #i3 as window manager
programs+=("mpv") #MPV as multimidia player
programs+=("flameshot") #Screenshooter
programs+=("simplescreenrecorder") #Screen recorder
programs+=("ttf-dejavu" "noto-fonts" "noto-fonts-emoji" "adobe-source-han-sans-otc-fonts" "adobe-source-code-pro-fonts") #Fonts
programs+=("imv") #Image viewer
programs+=("zip" "unrar" "tar" "unzip" "gzip") #For handling archives
programs+=("transmission-gtk") #Torrent client
programs+=("thunderbird") #Email client
programs+=("cmus") #A command line music player
programs+=("jre-openjdk" "jdk-openjdk" "maven") #Java OpenJDK and Maven
programs+=("youtube-dl") #For downloading youtube videos and other sites
programs+=("man-db") #Commands manual
programs+=("ntfs-3g") #Handling NTFS filesystems
programs+=("lm_sensors") #Sensors command
programs+=("dunst") #Desktop notifications
programs+=("dmenu") #Lightweight program menu for X



exec pacman -S --needed ${programs[*]}
