#!/bin/bash
path="$PWD"
cd "$HOME"

files="$path/config-files"
musics="$path/update-musics"
lazer="$path/update-lazer"
xinit="$files/.xinitrc"
git="$files/.gitconfig"
dunst="$files/dunstrc"
nvim="$files/init.vim"
vimplug="$files/plug.vim"
coc="$files/coc-settings.json"

echo "Creating folders..."

#Create folders that I normally use.
for folder in "Documents" "Downloads" "Musics"
do
	mkdir -v "$folder"
done

sleep 1
echo "Moving config files..."

if [ ! -f ".gitconfig" ]; then
	cp -v "$git" "$PWD"
fi

if [ ! -f ".xinitrc" ]; then
	cp -v "$xinit" "$PWD"
fi

if [ ! -f ".config/dunst/dunstrc" ]; then
	mkdir -pv ".config/dunst"
	cp -v "$dunst" ".config/dunst/"
fi

if [ ! -f ".config/nvim/init.vim" ]; then
	mkdir -pv ".config/nvim"
	cp -v "$nvim" ".config/nvim/"
	cp -v "$coc" ".config/nvim/"
fi

sleep 1
echo "Moving scripts..."

if [ ! -f "Applications/osu-lazer/update-lazer" ]; then
	mkdir -pv "Applications/osu-lazer"
	cp -v "$lazer" "Applications/osu-lazer/"
fi

if [ ! -f "Musics/update-musics" ]; then
	cp -v "$musics" "Musics/"
fi

sleep 1
echo "Adding vim-plug to nvim..."

if [ ! -f ".local/share/nvim/site/autoload/plug.vim" ]; then
	mkdir -pv ".local/share/nvim/site/autoload/"
	cp -v "$vimplug" ".local/share/nvim/site/autoload/"
fi

sleep 1
echo "Starting pikaur installation..."

if [ -z "$(ls -a /bin/ | grep pikaur)" ]; then
	git clone "https://aur.archlinux.org/pikaur.git" "Downloads/pikaur"
	cd "Downloads/pikaur"
	makepkg -fsri
	cd ..
	rm -rdvf "pikaur/"
	cd "$PWD"
	echo "pikaur installed! now, remember some apps: minecraft-launcher, surf, usbimager and google-chrome."
fi

sleep 1
