#!/bin/bash

home="/home/bieel1503"
files="$PWD/config-files"
xres="$files/.Xresources"
xinit="$files/.xinitrc"
nobeep="$files/nobeep.conf"
numlock="$files/activate-numlock.conf"
i3="$files/i3/config"
i3status="$files/i3status/config"

#Create folders that i normally use.
for folder in "Documents" "Downloads" "Musics" "Applications"
do
	mkdir -v "$home/$folder"
done

if [ ! -f "$home/.Xresources" ]; then
	cp -v "$xres" "$home/.Xresources"
fi

if [ ! -f "$home/.xinitrc" ]; then
	cp -v "$xinit" "$home/.xinitrc"
fi

#Blacklist annoying beep module.
if [ ! -f "/etc/modprobe.d/nobeep.conf" ]; then
	cp -v "$nobeep" "/etc/modprobe.d/nobeep.conf"
fi

#Activate numlock on getty.
if [ ! -f "/etc/systemd/system/getty@.service.d/activate-numlock.conf" ]; then
	mkdir -pv "/etc/systemd/system/getty@.service.d/"
	cp -v "$numlock" "/etc/systemd/system/getty@.service.d/activate-numlock.conf"
fi

if [ ! -f "$home/.config/i3/config" ]; then
	mkdir -pv "$home/.config/i3"
	cp -v "$i3" "$home/.config/i3/config"
fi

if [ ! -f "$home/.config/i3status/config" ]; then
	mkdir -pv "$home/.config/i3status/"
	cp -v "$i3status" "$home/.config/i3status/config"
fi

#Add a boot entry. Where '/dev/sdX' and 'Y' are the drive and partition number where the ESP is located. This assume that you made the partitions using LABEL.
efibootmgr --disk /dev/sdX --part Y --create --label "Arch Linux" --loader /vmlinuz-linux --unicode 'root=LABEL=linux_root rw initrd=\initramfs-linux.img initrd=\intel-ucode.img' --verbose
echo "Boot entry created? Remember to set a boot order!"
